#playbook qui install wordpress sur conteneur docker a partir du docker-compose et des roles
---
- hosts: 172.31.22.199
  become: true

#installation de docker-compose avant le lancement du role
  pre_tasks:
    - name: Install docker-compose
      get_url:
        url: https://github.com/docker/compose/releases/download/1.29.2/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: '0755'
#definition du role et toutes ces variable
  roles:
    - role: ansible-role-containerized-wordpress
